apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: academic-cluster
  region: us-east-1
  version: "1.28"

managedNodeGroups:
- name: ng-1
  minSize: 2
  maxSize: 5
  desiredCapacity: 3
  instanceType: t3.medium
  ssh:
    publicKeyName: eks-key
  labels:
    role: worker
  tags:
    Environment: development
    Project: academic-api
