apiVersion: apps/v1
kind: Deployment
metadata:
  name: university-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: university-api
  template:
    metadata:
      labels:
        app: university-api
    spec:
      containers:
        - name: api
          image: 654654436071.dkr.ecr.ap-southeast-1.amazonaws.com/university-api:latest
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secret
